spring:
  mail:
    host: smtp.mailjet.com
    port: 587
    username: ${COPYTRELLO_MAILJET_API_KEY}
    password: ${COPYTRELLO_MAILJET_SECRET_KEY}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

  application:
    name: task-tracker-email-sender
  kafka:
    bootstrap-servers: localhost:9092
  email:
    from-address: copytrelloteam@gmail.com
server:
  port: 8000
