spring:
  profiles:
    active: jwt
  application:
    name: copytrello
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/copytrello_db
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-IDENTITY: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
    show-sql: true
  flyway:
    schemas: users
    enabled: true
server:
  port: 8300
  servlet:
    context-path: /copytrello
  data:
    redis:
      host: localhost
      port: 6379



