spring:
  profiles:
    active: jwt
  application:
    name: copytrello
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-ctmjg352ng1s73bcpoj0-a/copytrello_db
    username: copytrello_db_user
    password: xm9I5M5NpCl7LXGHiPwLq9ymXeN8AjQJ
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
    show-sql: true
  flyway:
    enabled: true
server:
  port: 8300
  servlet:
    context-path: /copytrello
