spring:
  profiles:
    active: jwt
  application:
    name: copytrello
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgresql://copytrello_db_user:xm9I5M5NpCl7LXGHiPwLq9ymXeN8AjQJ@dpg-ctmjg352ng1s73bcpoj0-a/copytrello_db
    username: copytrello
    password: copytrello2024
  jpa:
    hibernate:
      ddl-IDENTITY: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
    show-sql: true
  flyway:
    schemas: users
    enabled: true
server:
  port: 8300
  servlet:
    context-path: /copytrello
  data:
    redis:
      host: localhost
      port: 6379
