spring:
  profiles:
    active: jwt
  application:
    name: copytrello
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
    show-sql: true
  flyway:
    enabled: true
server:
  port: ${PORT:8080}

  servlet:
    context-path: /copytrello
