spring:
  application:
    name: task-tracker-scheduler
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8880
scheduling:
  cron: "0 */5 * * * ?"