spring:
  application:
    name: task-tracker-scheduler
  datasource:
    url: jdbc:postgresql://localhost:5431/copytrello_db
    password: ${POSTGRES_PASSWORD}
server:
  port: 8880
scheduling:
  cron: "0 */5 * * * ?"