name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./task-tracker-backend
          tags: repinskie/task-tracker-backend:latest

      - name: Build and push scheduler image
        uses: docker/build-push-action@v2
        with:
          context: ./task-tracker-scheduler
          tags: repinskie/task-tracker-scheduler:latest

      - name: Build and push email-sender image
        uses: docker/build-push-action@v2
        with:
          context: ./task-tracker-email-sender
          tags: repinskie/task-tracker-email-sender:latest
